#!/bin/bash

GAME_ID=$1
TEMP_DIR=$2     # '/temp'
APP_DIR=$3      # '/app'

rm -rf $TEMP_DIR
mkdir $TEMP_DIR
cd $TEMP_DIR
rm -rf dominus

echo ""
echo "--- cloning branch $GAME_ID of dominus into $TEMP_DIR"
git clone -b $GAME_ID https://github.com/dan335/dominus.git

echo "--- building"
cd dominus
rm -rf $TEMP_DIR/bundle
meteor build --directory $TEMP_DIR

echo "--- running npm install"
cd $TEMP_DIR
cd bundle/programs/server
npm install

echo "--- stopping app"
sv down dominus

echo "--- moving to $APP_DIR"
rm -rf $APP_DIR
cd $TEMP_DIR
mv bundle $APP_DIR

echo "--- starting app"
sv up dominus

echo ""
